spring:
  cloud:
    stream:
      instance-count: 3
      instance-index: 2
      kafka:
        binder:
          brokers: localhost:9092,localhost:9093,localhost:9094
          auto-add-partitions: true
          auto-create-topics: true
          min-partition-count: 1
      bindings:
        mychannel:
          destination: stream-my
          group: my
          consumer:
            concurrency: 1
            partitioned: false